services:
  postgres:
    image: postgres:16
    container_name: postgres_db_test
    environment:
      POSTGRES_DB: reviewers_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  flyway:
    image: flyway/flyway:11.14.0
    container_name: flyway_migrations
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations/postgres:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/reviewers_test
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_CONNECT_RETRIES: 60
    command: -connectRetries=60 migrate
    working_dir: /flyway
    networks:
      - internal


networks:
  internal: